version: '3'
services:
  api:
    depends_on:
      - db
    container_name: api
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
  proxy:
    container_name: proxy
    depends_on:
      - api
    ports:
      - 8080:80
      - 8443:443
    build: 
      context: ./proxy
      dockerfile: Dockerfile
  db:
    container_name: db
    image: postgres:15.1
    environment:
      - POSTGRES_DB=mantella
      - POSTGRES_USER=mantella
      - POSTGRES_PASSWORD=mantella123321
    ports:
      - 5432:5432


