version: '3'
services:
  web-frontend:
    # ports:
    #   - 3000:3000
    build: 
      context: ./src/frontend
      dockerfile: Dockerfile
  api:
    # ports:
    #   - 8080:8080
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
  proxy:
    depends_on:
      - api
      - web-frontend
    ports:
      - 8080:80
      - 8443:443
    build: 
      context: ./proxy
      dockerfile: Dockerfile
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=mantella
      - POSTGRES_USER=mantella
      - POSTGRES_PASSWORD=mantella123321
    ports:
      - 5432:5432


