"""create table

Revision ID: 37e2d4c0d500
Revises: 91f55a0bc46b
Create Date: 2024-03-29 15:08:48.219485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e2d4c0d500'
down_revision = '91f55a0bc46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bug', sa.Column('test_case_execution_id', sa.Integer(), nullable=True))
    op.add_column('bug', sa.Column('check_list_execution_id', sa.Integer(), nullable=True))
    op.drop_index('ix_bug_check_list_id', table_name='bug')
    op.drop_index('ix_bug_test_case_id', table_name='bug')
    op.create_index(op.f('ix_bug_check_list_execution_id'), 'bug', ['check_list_execution_id'], unique=False)
    op.create_index(op.f('ix_bug_test_case_execution_id'), 'bug', ['test_case_execution_id'], unique=False)
    op.drop_constraint('bug_test_case_id_fkey', 'bug', type_='foreignkey')
    op.drop_constraint('bug_check_list_id_fkey', 'bug', type_='foreignkey')
    op.create_foreign_key(None, 'bug', 'test_case_execution', ['test_case_execution_id'], ['id'])
    op.create_foreign_key(None, 'bug', 'check_list_execution', ['check_list_execution_id'], ['id'])
    op.drop_column('bug', 'test_case_id')
    op.drop_column('bug', 'check_list_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bug', sa.Column('check_list_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bug', sa.Column('test_case_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bug', type_='foreignkey')
    op.drop_constraint(None, 'bug', type_='foreignkey')
    op.create_foreign_key('bug_check_list_id_fkey', 'bug', 'check_list', ['check_list_id'], ['id'])
    op.create_foreign_key('bug_test_case_id_fkey', 'bug', 'test_case', ['test_case_id'], ['id'])
    op.drop_index(op.f('ix_bug_test_case_execution_id'), table_name='bug')
    op.drop_index(op.f('ix_bug_check_list_execution_id'), table_name='bug')
    op.create_index('ix_bug_test_case_id', 'bug', ['test_case_id'], unique=False)
    op.create_index('ix_bug_check_list_id', 'bug', ['check_list_id'], unique=False)
    op.drop_column('bug', 'check_list_execution_id')
    op.drop_column('bug', 'test_case_execution_id')
    # ### end Alembic commands ###
