"""Databasecreate

Revision ID: 578eb029ba08
Revises: 
Create Date: 2024-02-22 16:39:36.990335

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '578eb029ba08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_list',
                    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('check_list_item',
                    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
                    sa.Column('check_list_id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['check_list_id'], ['check_list.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('test_case',
                    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('priority', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('test_case_step',
                    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
                    sa.Column('test_case_id', sa.Integer(), nullable=False),
                    sa.Column('order', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('expected_result', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_check_list_item_check_list_id'), 'check_list_item', ['check_list_id'], unique=False)
    op.create_index(op.f('ix_test_case_step_test_case_id'), 'test_case_step', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_case_step_test_case_id'), table_name='test_case_step')
    op.drop_table('test_case_step')
    op.drop_index(op.f('ix_check_list_item_check_list_id'), table_name='check_list_item')
    op.drop_table('check_list_item')
    op.drop_table('test_case')
    op.drop_table('check_list')
    # ### end Alembic commands ###
